#     __  __           __              
#    / / / /___ ______/ /_  ____  _____
#   / /_/ / __ `/ ___/ __ \/ __ \/ ___/
#  / __  / /_/ / /  / /_/ / /_/ / /    
# /_/ /_/\__,_/_/  /_.___/\____/_/     
#                              
# Version 1.2 created by TechToolbox (@nkomarn)

# Ahoy, matey! You've arrived at the configuration file, where things get scary. 
# Every single thing within this plugin is customizable (at least I tried to make it that way),
# so every message and plugin module can be modified here. If you would like to report a bug
# or suggest a feature, make sure to add an issue on the GitHub page for this plugin!
# GitHub URL: https://github.com/nkomarn/Harbor

values:
  # Name of the main world (used to set time to day when skipping night)
  worldname: "world"
  # How often (in seconds) to check if a player is in a bed
  sleepingCheck: 1

features: 
  # Skips night if more than half of players are sleeping
  skipnight: true

messages:
  chat:
    # Enable/Disable chat messages
    chatSwitch: true
    # Night skipped message
    nightSkippedMessage: "&eThe night has been skipped."
    # Display which player went to bed in chat
    playerSleepingMessage: "&e[player] is now sleeping ([sleeping]/[online])."
  actionbar:
    # Enable/Disable actionbar message
    actionbarSwitch: true
    # Shown when some players are in bed
    sleepingMessage: "&e%sleeping% out of %online% players are sleeping."
    # Shown when all players are in bed
    allSleepingMessage: "&eEveryone is sleeping. Sweet dreams!"