name: Harbor
version: 1.1
main: techtoolbox.Harbor.Main
description: Ahoy, matey! Harbor is a Spigot plugin that redefines how sleep works in your server, making it easier for all the online players to get in bed quick and skip through the night!
author: TechToolbox
